// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: test_LCD

#ifndef _TEST_LCD_UI_H
#define _TEST_LCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image8;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Panel7;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Button13;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_rainy_png);    // assets/rainy.png
LV_IMG_DECLARE(ui_img_celsius_png);    // assets/celsius.png
LV_IMG_DECLARE(ui_img_1670780937);    // assets/wi-fi.png
LV_IMG_DECLARE(ui_img_676135747);    // assets/Traffic Sign-1.png
LV_IMG_DECLARE(ui_img_676132672);    // assets/Traffic Sign-2.png
LV_IMG_DECLARE(ui_img_frame_381_png);    // assets/Frame 381.png
LV_IMG_DECLARE(ui_img_frame_374_png);    // assets/Frame 374.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_night_png);    // assets/night.png
LV_IMG_DECLARE(ui_img_next_png);    // assets/next.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/arrow.png
LV_IMG_DECLARE(ui_img_2057797228);    // assets/light-bulb-offoff.png
LV_IMG_DECLARE(ui_img_1536731275);    // assets/light-bulb.png
LV_IMG_DECLARE(ui_img_fire_urn_png);    // assets/fire_urn.png
LV_IMG_DECLARE(ui_img_4138409);    // assets/20231226-112236.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
